//header automatically generated by autoHead
#pragma once
#include "hashMap.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
void printEnt(Entry* ent);
//int strcmpWrap(void* a, void* b){
  //  return strcmp((char*)a,(char*)b);
//}
int unitTests();
